module.exports = {
  AddReactions: "Añadir Reacciones",
  Administrator: "Administrador",
  AttachFiles: "Adjuntar archivos",
  BanMembers: "Expulsar miembros",
  ChangeNickname: "Cambiar apodo",
  Connect: "Conectar",
  CreateInstantInvite: "Crear invitación instantánea",
  CreatePrivateThreads: "Crear hilos privados",
  CreatePublicThreads: "Crear hilos públicos",
  DeafenMembers: "Silenciar miembros",
  EmbedLinks: "Insertar enlaces",
  KickMembers: "Expulsar miembros",
  ManageChannels: "Gestionar canales",
  ManageEmojisAndStickers: "Gestionar emojis y pegatinas",
  ManageEvents: "Gestionar Eventos",
  ManageGuild: "Gestionar servidor",
  ManageMessages: "Gestionar mensajes",
  ManageNicknames: "Gestionar apodos",
  ManageRoles: "Gestionar roles",
  ManageThreads: "Gestionar hilos",
  ManageWebhooks: "Gestionar webhooks",
  MentionEveryone: "Mencionar a todos",
  ModerateMembers: "Moderar miembros",
  MoveMembers: "Mover miembros",
  MuteMembers: "Silenciar miembros",
  PrioritySpeaker: "Orador prioritario",
  ReadMessageHistory: "Leer historial de mensajes",
  RequestToSpeak: "Solicitar hablar",
  SendMessages: "Enviar mensajes",
  SendMessagesInThreads: "Enviar mensajes en hilos",
  SendTTSMessages: "Enviar mensajes de texto a voz",
  Speak: "Hablar",
  Stream: "Transmitir video",
  UseApplicationCommands: "Usar comandos de la aplicación",
  UseEmbeddedActivities: "Usar actividades integradas",
  UseExternalEmojis: "Usar emojis externos",
  UseExternalStickers: "Usar pegatinas externas",
  UseVAD: "Usar actividad de voz",
  ViewAuditLog: "Ver registro de auditoría",
  ViewChannel: "Ver canal",
  ViewGuildInsights: "Ver información del servidor",
};
